version: "3.7"

services:
    db:
        image: postgres:14.3
        restart: always
        ports:
            - "5432:5432"
        environment:
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_USER: ${DB_USER}
            POSTGRES_DB: ${DB_NAME}
        expose:
            - "5432"
        volumes:
            - ./docker-postgres-init.sql:/docker-entrypoint-initdb.d/docker-postgres-init.sql
    redis:
        image: redis
        ports:
            - '6379:6379'
        #command: redis-server --requirepass ${REDIS_PASSWORD}
        command: redis-server
    backend:
        build: .
        ports:
            - "3000:3000"
        volumes:
            - ./.:/home/node/code
            - /home/node/code/node_modules
        depends_on:
            - db
            - redis
